### ISSUE TITLE
More on installing error. 

### ISSUE THREAD

**Issue by magicbruno** [umehara-lp/Simple-Sftp-Upload#6]
I suggest to reopen closed isue on Simple-Sftp-Upload because solution is very, very simple:
I found that in my enviroments (Windows 10, language it) app init fails when tries to add a new item to main menu. This happens because the STRINGS variable that should contain app localized strings is an empty object. I found this solution.
I created a root entry in au.brackets-simple-sftp-upload\nls\Strings.js:
```
define( function( require, exports, module ) {
	'use strict';	
	module.exports = {
		root: true,
		en: true,
		ja: true
	};
} );
```
and a corresponding Strings.js file in au.brackets-simple-sftp-upload\nls\root copying content of au.brackets-simple-sftp-upload\nls\en\Strings.js. 
Now the extension loads as expected and new menu item is created correctly..
NOTE: Changing language in my enviroment had non effects.

**Comment by umehara-lp** [comment]
Thank you very much.
I tried to comply, please check the latest version.

**Comment by magicbruno** [comment]
Now it's ok.
